const express=require("express")
const lbRouter=require('./router/dota2_lbimg.js')
const bbRouter=require('./router/dota2_bbimg.js')
const hdRouter=require('./router/dota2_hdimg.js')
const llbRouter=require('./router/dota2_llbimg.js')
const ndata=require('./router/dota2_data.js')
const Otherimg=require('./router/dota2_othenrimg.js')
const problem=require('./router/dota2_problem.js')
const news=require('./router/dota2_news.js')
const newimg=require('./router/dota2_newtext.js')
const cors=require("cors")
var app=express();
app.use(express.static("public"))
app.listen(3000);
// const pool=require("./pool")

app.use(cors())
app.use(lbRouter)
app.use(bbRouter)
app.use(hdRouter)
app.use(llbRouter)
app.use(ndata)
app.use(Otherimg)
app.use(problem)
app.use(news)
app.use(newimg)